import React, { useState, useEffect } from 'react';
import { CheckCircle, Zap, Shield, FileText, Calendar, DollarSign } from 'lucide-react';
import { getAutoGeneratedCredits } from '../../api/api';

const AutoCreditsList = () => {
  const [autoCredits, setAutoCredits] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchAutoCredits();
  }, []);

  const fetchAutoCredits = async () => {
    try {
      setIsLoading(true);
      const response = await getAutoGeneratedCredits();
      setAutoCredits(response.data.auto_credits || []);
    } catch (error) {
      console.error('Error fetching auto-credits:', error);
      setError('Error fetching auto-generated credits');
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-green-600"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="text-center py-12">
        <div className="text-red-600 mb-4">{error}</div>
        <button 
          onClick={fetchAutoCredits}
          className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
        >
          Retry
        </button>
      </div>
    );
  }

  if (autoCredits.length === 0) {
    return (
      <div className="text-center py-12">
        <Zap className="mx-auto h-12 w-12 text-gray-400 mb-4" />
        <h3 className="text-lg font-medium text-gray-900 mb-2">No Auto-Generated Credits Yet</h3>
        <p className="text-gray-500 mb-6">
          Submit H₂ production data through ML Verification to automatically generate credits and tokens.
        </p>
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 max-w-md mx-auto">
          <h4 className="font-medium text-blue-900 mb-2">🚀 How it works:</h4>
          <ul className="text-sm text-blue-800 space-y-1">
            <li>• Submit production data in ML Verification tab</li>
            <li>• AI automatically verifies and approves</li>
            <li>• Credit and token generated instantly</li>
            <li>• Government certificates auto-created</li>
          </ul>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-green-50 to-blue-50 border border-green-200 rounded-lg p-6">
        <div className="flex items-center space-x-3 mb-4">
          <Zap className="h-8 w-8 text-green-600" />
          <div>
            <h2 className="text-2xl font-bold text-gray-900">🚀 Auto-Generated Credits</h2>
            <p className="text-gray-600">ML-Verified H₂ production credits with blockchain tokens</p>
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-white rounded-lg p-4 border border-green-200">
            <div className="text-2xl font-bold text-green-600">{autoCredits.length}</div>
            <div className="text-sm text-gray-600">Total Auto-Credits</div>
          </div>
          <div className="bg-white rounded-lg p-4 border border-blue-200">
            <div className="text-2xl font-bold text-blue-600">
              {autoCredits.reduce((sum, credit) => sum + credit.amount, 0)} kg
            </div>
            <div className="text-sm text-gray-600">Total H₂ Verified</div>
          </div>
          <div className="bg-white rounded-lg p-4 border border-purple-200">
            <div className="text-2xl font-bold text-purple-600">
              ${autoCredits.reduce((sum, credit) => sum + credit.price, 0).toFixed(2)}
            </div>
            <div className="text-sm text-gray-600">Total Credit Value</div>
          </div>
        </div>
      </div>

      {/* Credits List */}
      <div className="space-y-4">
        {autoCredits.map((credit) => (
          <div key={credit.id} className="bg-white border border-green-200 rounded-lg p-6 shadow-sm hover:shadow-md transition-shadow">
            <div className="flex items-start justify-between mb-4">
              <div className="flex-1">
                <div className="flex items-center space-x-3 mb-2">
                  <CheckCircle className="h-5 w-5 text-green-600" />
                  <h3 className="text-lg font-semibold text-gray-900">{credit.name}</h3>
                  <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800">
                    ML-Approved
                  </span>
                </div>
                <p className="text-gray-600 mb-3">{credit.description || 'ML-verified hydrogen production credit'}</p>
              </div>
              <div className="text-right">
                <div className="text-2xl font-bold text-green-600">${credit.price}</div>
                <div className="text-sm text-gray-500">{credit.amount} kg H₂</div>
              </div>
            </div>

            {/* Token Information */}
            <div className="bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg p-4 mb-4">
              <div className="flex items-center space-x-2 mb-3">
                <Shield className="h-5 w-5 text-blue-600" />
                <h4 className="font-medium text-blue-900">Blockchain Token Generated</h4>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <div className="text-sm font-medium text-gray-700 mb-1">Token ID:</div>
                  <div className="font-mono text-sm bg-white px-3 py-2 rounded border text-blue-800">
                    {credit.token_id}
                  </div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-700 mb-1">Production Method:</div>
                  <div className="text-sm text-gray-900">{credit.production_method}</div>
                </div>
              </div>
            </div>

            {/* Details Grid */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="flex items-center space-x-2">
                <Calendar className="h-4 w-4 text-gray-400" />
                <div>
                  <div className="text-xs text-gray-500">Verified Date</div>
                  <div className="text-sm font-medium text-gray-900">
                    {new Date(credit.verification_date).toLocaleDateString()}
                  </div>
                </div>
              </div>
              <div className="flex items-center space-x-2">
                <Zap className="h-4 w-4 text-gray-400" />
                <div>
                  <div className="text-xs text-gray-500">ML Score</div>
                  <div className="text-sm font-medium text-gray-900">{credit.ml_score}/100</div>
                </div>
              </div>
              <div className="flex items-center space-x-2">
                <FileText className="h-4 w-4 text-gray-400" />
                <div>
                  <div className="text-xs text-gray-500">Documents</div>
                  <div className="text-sm font-medium text-gray-900">Auto-Generated</div>
                </div>
              </div>
              <div className="flex items-center space-x-2">
                <DollarSign className="h-4 w-4 text-gray-400" />
                <div>
                  <div className="text-xs text-gray-500">Status</div>
                  <div className="text-sm font-medium text-green-600">Active & Verified</div>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default AutoCreditsList;
